"""Add descuento column to ComprobanteItem

Revision ID: 09dff5b59682
Revises: 5f266ce60c8d
Create Date: 2026-03-04 18:32:41.157316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dff5b59682'
down_revision = '5f266ce60c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobante_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobante_items', schema=None) as batch_op:
        batch_op.drop_column('descuento')

    # ### end Alembic commands ###
