"""modelo inicial completo

Revision ID: 5f266ce60c8d
Revises: 
Create Date: 2026-02-25 16:44:41.987441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f266ce60c8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=15), nullable=False),
    sa.Column('nombres', sa.String(length=200), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=True),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('costos_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('colorcode', sa.String(length=100), nullable=True),
    sa.Column('sizecode', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('costos_productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_costos_productos_sku'), ['sku'], unique=False)

    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('plantillas_comprobante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('es_activo', sa.Boolean(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('css_content', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_sin_igv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=True),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('fecha_sincronizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_sku'), ['sku'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('ip_registro', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento_sunat', sa.String(length=2), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('correlativo', sa.String(length=10), nullable=False),
    sa.Column('numero_completo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('numero_orden', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_operaciones_gravadas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_operaciones_exoneradas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_operaciones_inafectas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_operaciones_gratuitas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_igv', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio_sunat', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('cdr_path', sa.String(length=500), nullable=True),
    sa.Column('hash_cpe', sa.String(length=100), nullable=True),
    sa.Column('mensaje_sunat', sa.Text(), nullable=True),
    sa.Column('codigo_sunat', sa.String(length=10), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('comprobante_referencia_id', sa.Integer(), nullable=True),
    sa.Column('motivo_codigo', sa.String(length=5), nullable=True),
    sa.Column('motivo_descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['comprobante_referencia_id'], ['comprobantes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie', 'correlativo', name='uq_serie_correlativo')
    )
    op.create_table('producto_categorias',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('variaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_sin_igv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=True),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('atributos', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variaciones_sku'), ['sku'], unique=False)

    op.create_table('comprobante_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('producto_nombre', sa.String(length=300), nullable=False),
    sa.Column('producto_sku', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=5), nullable=True),
    sa.Column('precio_unitario_con_igv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario_sin_igv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igv_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_sin_igv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igv_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_con_igv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_afectacion_igv', sa.String(length=2), nullable=True),
    sa.Column('variacion_id', sa.Integer(), nullable=True),
    sa.Column('atributos_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprobante_items')
    with op.batch_alter_table('variaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variaciones_sku'))

    op.drop_table('variaciones')
    op.drop_table('usuario_roles')
    op.drop_table('rol_permisos')
    op.drop_table('producto_categorias')
    op.drop_table('comprobantes')
    op.drop_table('usuarios')
    op.drop_table('roles')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_sku'))

    op.drop_table('productos')
    op.drop_table('plantillas_comprobante')
    op.drop_table('permisos')
    with op.batch_alter_table('costos_productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_costos_productos_sku'))

    op.drop_table('costos_productos')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
