"""add es_bulk to comprobantes

Revision ID: d15766f064bc
Revises: 09dff5b59682
Create Date: 2026-03-05 17:18:50.433148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15766f064bc'
down_revision = '09dff5b59682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_bulk', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.drop_column('es_bulk')

    # ### end Alembic commands ###
